### ISSUE TITLE
No Tags or Releases

### ISSUE THREAD

**Issue by nickalbrecht** [slovely/OverlappingFeatureSpiderfier#6]
This isn't really a issue with the source per se, but I wanted to point it out none the less. I stumbled across this today and it's exactly what I was looking for. However I tried to add a dependency to this through the jsDelivr CDN since it can reference content inside of GitHub repos. However it appears that there's a requirement for the repo to have at least one tag or version/release in it, so that a RUL can be locked to one specific version of the file? At least that's my guess after fighting with this for a little while. For the moment I'll just copy the file into my project and use it directly from there.

**Comment by slovely** [comment]
Hi Nick... I've created a release now, never used jsDelivr though, but let me know if that solves your issue!

**Comment by nickalbrecht** [comment]
Yup that worked! It's now reachable using a URL like this. https://cdn.jsdelivr.net/gh/slovely/OverlappingFeatureSpiderfier@1.0/build/OverlappingFeatureSpiderfier.js

**Comment by slovely** [comment]
Thanks Nick :)
